In [17]:
# Importing all required packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Import dataset
cardata = pd.read_csv('CarPrice_Assignment.csv')

In [18]:
# Top rows
cardata.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [3]:
# Check the no of records
cardata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
car_ID              205 non-null int64
symboling           205 non-null int64
CarName             205 non-null object
fueltype            205 non-null object
aspiration          205 non-null object
doornumber          205 non-null object
carbody             205 non-null object
drivewheel          205 non-null object
enginelocation      205 non-null object
wheelbase           205 non-null float64
carlength           205 non-null float64
carwidth            205 non-null float64
carheight           205 non-null float64
curbweight          205 non-null int64
enginetype          205 non-null object
cylindernumber      205 non-null object
enginesize          205 non-null int64
fuelsystem          205 non-null object
boreratio           205 non-null float64
stroke              205 non-null float64
compressionratio    205 non-null float64
horsepower          205 non-null int64
peakrpm             205 non-null int64
citympg             205 non-null int64
highwaympg          205 non-null int64
price               205 non-null float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.7+ KB

In [4]:
# Requirement - You need to consider only company name as the independent variable for model building. 
cardata['CarName'] = cardata.CarName.str.split().str.get(0)

In [5]:
cardata.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [11]:
# Data Preparation

# Dropping columns
cardata.drop(['car_ID'],axis=1,inplace=True)

In [13]:
# convert categorical variables
cardata.apply(pd.Series.nunique)

symboling             6
CarName              28
fueltype              2
aspiration            2
doornumber            2
carbody               5
drivewheel            3
enginelocation        2
wheelbase            53
carlength            75
carwidth             44
carheight            49
curbweight          171
enginetype            7
cylindernumber        7
enginesize           44
fuelsystem            8
boreratio            38
stroke               37
compressionratio     32
horsepower           59
peakrpm              23
citympg              29
highwaympg           30
price               189
dtype: int64

In [19]:
symboling = pd.get_dummies(cardata['symboling'], prefix=['symboling'], drop_first=True)
fueltype = pd.get_dummies(cardata['fueltype'], prefix=['fueltype'], drop_first=True)
aspiration = pd.get_dummies(cardata['aspiration'], prefix=['aspiration'], drop_first=True)
doornumber = pd.get_dummies(cardata['doornumber'], prefix=['doornumber'], drop_first=True)
carbody = pd.get_dummies(cardata['carbody'], prefix=['carbody'], drop_first=True)
drivewheel = pd.get_dummies(cardata['drivewheel'], prefix=['drivewheel'], drop_first=True)
enginelocation = pd.get_dummies(cardata['enginelocation'], prefix=['enginelocation'], drop_first=True)
enginetype = pd.get_dummies(cardata['enginetype'], prefix=['enginetype'], drop_first=True)
cylindernumber = pd.get_dummies(cardata['cylindernumber'], prefix=['cylindernumber'], drop_first=True)
fuelsystem = pd.get_dummies(cardata['fuelsystem'], prefix=['fuelsystem'], drop_first=True)

In [15]:
#Adding the results to the main dataframe
cardata = pd.concat([cardata,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,enginetype,cylindernumber,fuelsystem],axis=1)

In [16]:
# Dropping the variables
housing.drop(['furnishingstatus'],axis=1,inplace=True)

cardata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 59 columns):
symboling           205 non-null int64
CarName             205 non-null object
fueltype            205 non-null object
aspiration          205 non-null object
doornumber          205 non-null object
carbody             205 non-null object
drivewheel          205 non-null object
enginelocation      205 non-null object
wheelbase           205 non-null float64
carlength           205 non-null float64
carwidth            205 non-null float64
carheight           205 non-null float64
curbweight          205 non-null int64
enginetype          205 non-null object
cylindernumber      205 non-null object
enginesize          205 non-null int64
fuelsystem          205 non-null object
boreratio           205 non-null float64
stroke              205 non-null float64
compressionratio    205 non-null float64
horsepower          205 non-null int64
peakrpm             205 non-null int64
citympg             205 non-null int64
highwaympg          205 non-null int64
price               205 non-null float64
-1                  205 non-null uint8
0                   205 non-null uint8
1                   205 non-null uint8
2                   205 non-null uint8
3                   205 non-null uint8
gas                 205 non-null uint8
turbo               205 non-null uint8
two                 205 non-null uint8
hardtop             205 non-null uint8
hatchback           205 non-null uint8
sedan               205 non-null uint8
wagon               205 non-null uint8
fwd                 205 non-null uint8
rwd                 205 non-null uint8
rear                205 non-null uint8
dohcv               205 non-null uint8
l                   205 non-null uint8
ohc                 205 non-null uint8
ohcf                205 non-null uint8
ohcv                205 non-null uint8
rotor               205 non-null uint8
five                205 non-null uint8
four                205 non-null uint8
six                 205 non-null uint8
three               205 non-null uint8
twelve              205 non-null uint8
two                 205 non-null uint8
2bbl                205 non-null uint8
4bbl                205 non-null uint8
idi                 205 non-null uint8
mfi                 205 non-null uint8
mpfi                205 non-null uint8
spdi                205 non-null uint8
spfi                205 non-null uint8
dtypes: float64(8), int64(7), object(10), uint8(34)
memory usage: 46.9+ KB

In [7]:
# Putting feature variable to X
X = cardata.iloc[:, :24]
# Putting feature variable to Y
Y = cardata.iloc[:, 25]

In [9]:
# Splitting the data into training and test
from sklearn.cross_validation import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, Y, train_size=0.7 , random_state=100)

In [10]:
# Perform linear regression
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(X_train,y_train)

ValueError: could not convert string to float: 'mpfi'